---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pathway Analysis: Gene Set Enrichment Analysis Using `fgsea`


<https://stephenturner.github.io/deseq-to-fgsea/>

### Install the Package

If you haven't already installed `fgsea`, uncomment the code in the chunk below and install it

```{r}
#BiocManager::install('fgsea')
```

### Gene Set Enrichment Analysis (GSEA)

Run through with our example data and other data because nothing comes up in ours

```{r}
diff_exp_tbl %>%
  dplyr::select(gene, stat) %>%
  na.omit() %>%
  distinct() %>%
  group_by(gene) %>%
  summarize(stat = mean(stat)) -> gene_res
```

```{r}
ranks <- deframe(gene_res)

ranks %>% head()
```

```{r}
# use Reactome pathways
pathways <- reactomePathways(names(exampleRanks))
```

```{r}
fgsea_res <- fgsea(pathways = pathways, stats = ranks, nperm = 10000)
```

```{r}
collapsed_pathways <- collapsePathways(fgsea_res, 
                                       pathways = pathways, 
                                       stats = ranks)
```

```{r}
fgsea_res %>%
  as_tibble()
fgsea_res_tidy

getwd()
```






